services:
  # Main Web Service
  - type: web
    name: table-for-two
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: table-for-two-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: "dating_backend.py"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: REDIS_URL
        fromService:
          name: table-for-two-redis
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: APP_BASE_URL
        value: "https://tablefortwo.com"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: FIELD_ENCRYPTION_KEY
        generateValue: true

  # Celery Worker
  - type: worker
    name: table-for-two-celery
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: ./startup_celery.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: C_FORCE_ROOT
        value: "1"
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: table-for-two-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: table-for-two-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: "dating_backend.py"
      - key: SYSTEM_EMAIL
        sync: false
      - key: SYSTEM_EMAIL_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  # Celery Beat Scheduler
  - type: worker
    name: table-for-two-celery-beat
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A celery_app beat --loglevel=INFO
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PRODUCTION
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: table-for-two-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: table-for-two-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: "dating_backend.py"

databases:
  - name: table-for-two-db
    databaseName: table_for_two
    user: tablefortwo_user
    plan: starter  # 1GB storage

# Redis instance
services:
  - type: redis
    name: table-for-two-redis
    plan: starter  # 100MB memory
